name: Test Server

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
        - uses: actions/checkout@v4

        # - uses: actions-rust-lang/setup-rust-toolchain@v1
        #   with:
        #     components: rustfmt, clippy

        - name: Check Formatting
          uses: actions-rust-lang/rustfmt@v1
  
        - name: Run Clippy
          run: cargo clippy
