name: Test Server

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production

    defaults:
      run:
        working-directory: server

    services:
      # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers#running-jobs-directly-on-the-runner-machine
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
        - uses: actions/checkout@v4

        - uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            components: rustfmt,clippy

        - name: Check Formatting
          uses: actions-rust-lang/rustfmt@v1
  
        - name: Run Clippy
          run: cargo clippy
