name: Test Server

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Use Cached SQLX CLI
        uses: actions/cache@v4
        with:
          path: target
          key: server-${{ runner.os }}-${{ hashFiles('$HOME/.cargo/registry/**/*') }}

      - name: Install SQLX CLI
        run: cargo install sqlx-cli

      - name: Run Migrations
        env:
          DATABASE_URL: postgresql://postgres:password@postgres/floppy
        run: sqlx migrate run

      - name: Use Cached Build
        uses: actions/cache@v4
        with:
          path: target
          key: server-${{ runner.os }}-${{ hashFiles('server/Cargo.lock') }}

      - name: Build Project
        env:
          DATABASE_URL: postgresql://postgres:password@postgres/floppy
        run: cargo build

      - name: Check Formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy
